Repository tesu-tesu/antrian-sehat-frontend, pull requests merged in 2020-10, with the labels that each got.

#40 User - List Poli Page
  react-basic/package-lock.json
  react-basic/package.json
  react-basic/src/constants/urls.js
  react-basic/src/index.css
  react-basic/src/pages/ListPolyclinic.js
  react-basic/src/routes.js
Labels: enhancement

#46 Dynamic Polyclinic of Health Agency
  react-basic/src/pages/ListPolyclinic.js
Labels: documentation

#49 Change to const route list polyclinic
  react-basic/src/constants/urls.js
  react-basic/src/pages/ListPolyclinic.js
Labels: bug

#60 keyPressed enter on login form
  react-basic/src/pages/Login.js
Labels: documentation

#62 simplify routing usere each role
  react-basic/src/App.js
  react-basic/src/components/PasienRoute.js
  react-basic/src/components/PrivateRoute.js
  react-basic/src/pages/Login.js
  react-basic/src/routes/admin_routes.js
  react-basic/src/routes/patient_routes.js
  react-basic/src/routes/routes.js
Labels: bug

#64 simplify route user each role v2
  react-basic/src/App.js
Labels: clean-code

#69 Make Login & Register page responsive with all screen (cek desc) v2
  react-basic/src/images/pasien/LOGIN 4.png
  react-basic/src/images/pasien/REGISTER.png
Labels: bug

#71 Make Login & Register page responsive with all screen (cek desc) v3
  react-basic/src/images/pasien/LOGIN 4.png
  react-basic/src/images/pasien/LOGIN.png
  react-basic/src/images/pasien/LOGIN2.png
  react-basic/src/images/pasien/REGISTER.png
  react-basic/src/pages/Login.js
  react-basic/src/pages/Register.js
Labels: bug

#80 Make Login & Register page responsive with all screen (cek desc) v4
  react-basic/src/pages/Login.js
  react-basic/src/pages/Register.js
Labels: bug
